BerryVillage_House1_MapScripts::
	.byte 0


BerryVillage_House1_BlendMaster::
	lock
	faceplayer
	msgbox BerryVillage_House1_BlendMaster_Text_0
	releaseall
	end


BerryVillage_House1_BlendMaster_Text_0:
	.string "They call me the Blend Master. I moved\n"
	.string "here after I heard about the Berry\l"
	.string "Master next door. With his magnificient\l"
	.string "berry knowledge I can create all the\l"
	.string "pokeblocks I want to.$"
