BerryVillage_ConstructionHouse_MapScripts::
	.byte 0


BerryVillage_ConstructionHouse_Worker1::
	lock
	faceplayer
	msgbox BerryVillage_ConstructionHouse_Worker1_Text_0
	releaseall
	end


BerryVillage_ConstructionHouse_Worker2::
	lock
	faceplayer
	msgbox BerryVillage_ConstructionHouse_Worker2_Text_0
	releaseall
	end


BerryVillage_ConstructionHouse_Dad::
	lock
	faceplayer
	msgbox BerryVillage_ConstructionHouse_Dad_Text_0
	releaseall
	end


BerryVillage_ConstructionHouse_BerryBoy::
	lock
	faceplayer
	msgbox BerryVillage_ConstructionHouse_BerryBoy_Text_0
	releaseall
	end


BerryVillage_ConstructionHouse_Worker1_Text_0:
	.string "This village has grown out of the\n"
	.string "construction work.\n"
	.string "I wonder what will happen with it once\l"
	.string "the job is done?$"

BerryVillage_ConstructionHouse_Worker2_Text_0:
	.string "I am telling you, constructing this road\n"
	.string "between LILYCOVE and MAUVILLE has\l"
	.string "been tough!\n"
	.string "I can't wait for it to be over!$"

BerryVillage_ConstructionHouse_Dad_Text_0:
	.string "My son has a real knack for POKéMON\n"
	.string "battling.\n"
	.string "I am sure he will become a great trainer\l"
	.string "some day.$"

BerryVillage_ConstructionHouse_BerryBoy_Text_0:
	.string "I haven't given up! I know that with the\n"
	.string "right combination I can become the\l"
	.string "best trainer in the whole region using\l"
	.string "the power of berries!$"
